version: '3.5'
services:
  parsedmarc:
    build: ./parsedmarc/
    container_name: parsedmarc
    volumes:
      - ./files:/input:ro
      - ./output_files:/output
    command: parsedmarc -c /parsedmarc.ini /input/* --debug
    depends_on:
      - elasticsearch
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "5"


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: parsedmarc-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "5"

  

  grafana:
    build: ./grafana/
    container_name: parsedmarc_grafana
    logging:
      options:
        max-size: 10m
        max-file: "5"

    ports:
      - 3000:3000
    restart: always
    user: root
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
      GF_AUTH_ANONYMOUS_ENABLED: 'false'
    volumes:
      - grafana-storage:/var/lib/grafana

  
volumes:
  esdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./esdata

  grafana-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./grafana-storage
